version: '3'
services:
  pelican-sitebuilder:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8000"
    volumes:
      - .:/project-root
    environment:
      - CONFFILE=pelicanconf.py
    command: pelican -l content -s pelicanconf.py -r --bind 0.0.0.0
    #command: pelican -l content -s pelicanconf_landing.py -r --bind 0.0.0.0 